### ISSUE TITLE
Not working in V12

### ISSUE THREAD

**Issue by Xain3** [Gundancer/foundryvtt-roof-occlusion-vision-fade#4]
The title is pretty self-explanatory.

While the option displays correctly in V12 when you select "Also fade", the additional behaviour is unfortunately not applied.

### Log

```
Foundry VTT | Error thrown in hooked function 'bound updateTileConfig' for hook 'renderTileConfig'
#call @ foundry.js:635
callAll @ foundry.js:589
_callHooks @ foundry.js:5918
_render @ foundry.js:5879
await in _render
_render @ foundry.js:6572
_render @ foundry.js:7158
render @ foundry.js:5793
🎁call_wrapped @ libWrapper-wrapper.js:511
applicationRender @ uiscaler.js:87
🎁call_wrapper @ libWrapper-wrapper.js:639
🎁Application.prototype.render#0 @ libWrapper-wrapper.js:193
_onClickLeft2 @ foundry.js:27353
callback @ foundry.js:30834
#handleClickLeft2 @ foundry.js:31057
#handleLeftDown @ foundry.js:31016
#handlePointerDown @ foundry.js:30981
notifyListeners @ EventBoundary.ts:1454
notifyTarget @ EventBoundary.ts:662
propagate @ EventBoundary.ts:299
dispatchEvent @ EventBoundary.ts:210
mapPointerDown @ EventBoundary.ts:683
mapEvent @ EventBoundary.ts:231
onPointerDown @ EventSystem.ts:373Understand this warning
foundry.js:655 Error: Error thrown in hooked function 'bound updateTileConfig' for hook 'renderTileConfig'. Cannot set properties of undefined (setting 'src')
[Detected 1 package: df-architect(4.0.0)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at ActiveTileConfig._callHooks (foundry.js:5918:13)
    at ActiveTileConfig._render (foundry.js:5879:10)
    at async ActiveTileConfig._render (foundry.js:6572:5)
    at async ActiveTileConfig._render (foundry.js:7158:5)Caused by: TypeError: Cannot set properties of undefined (setting 'src')
[Detected 1 package: df-architect(4.0.0)]
    at TileConfigExt.updateImagePreview (TileConfigExt.ts:84:15)
    at TileConfigExt.updateTileConfig (TileConfigExt.ts:39:8)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at ActiveTileConfig._callHooks (foundry.js:5918:13)
    at ActiveTileConfig._render (foundry.js:5879:10)
    at async ActiveTileConfig._render (foundry.js:6572:5)
    at async ActiveTileConfig._render (foundry.js:7158:5)
```

EDIT: leaving the log for documentation, but the error was actually caused by a conflict with DF architect. The module still does not work as intended, though.

**Comment by Xain3** [comment]
Also, TileDocument#overhead appears to be deprecated

```
foundry-esm.js:4621 Error: TileDocument#overhead is deprecated.
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at get overhead (foundry-esm.js:16243:21)
    at Object.fn (RoofVisionFade.mjs:31:30)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Tile.applyRenderFlags (foundry.js:26658:11)
    at #applyRenderFlags (foundry.js:26282:44)
    at mn.emit (TickerListener.ts:71:47)
    at Pt.update (Ticker.ts:427:37)
    at Pt._tick (Ticker.ts:129:22)
    ```

**Comment by CapivaraTupiniquim** [comment]
v14?
